"use strict";
/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.0
 * 	protoc            v3.10.1
 * source: auth.proto
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    Object.defineProperty(o, k2, { enumerable: true, get: function() { return m[k]; } });
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Token = void 0;
const tsjson = __importStar(require("@llkennedy/protoc-gen-tsjson"));
const protoc_gen_tsjson_1 = require("@llkennedy/protoc-gen-tsjson");
const user_1 = require("user");
/** A message */
class Token extends Object {
    ToProtoJSON() {
        var _a, _b, _c;
        return {
            id: (_a = this.id) === null || _a === void 0 ? void 0 : _a.ToProtoJSON(),
            created: (_b = this.created) === null || _b === void 0 ? void 0 : _b.ToProtoJSON(),
            expires: (_c = this.expires) === null || _c === void 0 ? void 0 : _c.ToProtoJSON(),
        };
    }
    static Parse(data) {
        return __awaiter(this, void 0, void 0, function* () {
            let objData = tsjson.AnyToObject(data);
            let res = new Token();
            res.id = yield tsjson.Parse.Message(objData, "id", "id", user_1.UserID.Parse);
            res.created = yield tsjson.Parse.Message(objData, "created", "created", protoc_gen_tsjson_1.google.protobuf.Timestamp.Parse);
            res.expires = yield tsjson.Parse.Message(objData, "expires", "expires", protoc_gen_tsjson_1.google.protobuf.Timestamp.Parse);
            return res;
        });
    }
}
exports.Token = Token;
//# sourceMappingURL=auth.js.map