/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.0
 * 	protoc            v3.10.1
 * source: auth.proto
 */
import * as tsjson from "@llkennedy/protoc-gen-tsjson";
import { google } from "@llkennedy/protoc-gen-tsjson";
import { UserID as shared__UserID } from "user";
/** A message */
export declare class Token extends Object implements tsjson.ProtoJSONCompatible {
    /** A field */
    id?: shared__UserID;
    /** A field */
    created?: google.protobuf.Timestamp;
    /** A field */
    expires?: google.protobuf.Timestamp;
    ToProtoJSON(): Object;
    static Parse(data: any): Promise<Token>;
}
//# sourceMappingURL=auth.d.ts.map