/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.0
 * 	protoc            v3.10.1
 * source: user.proto
 */
import * as tsjson from "@llkennedy/protoc-gen-tsjson";
/** A message */
export declare class UserID extends Object implements tsjson.ProtoJSONCompatible {
    /** A field */
    uuid?: string;
    ToProtoJSON(): Object;
    static Parse(data: any): Promise<UserID>;
}
//# sourceMappingURL=user.d.ts.map