/**
 * Code generated by protoc-gen-tsjson. DO NOT EDIT.
 * versions:
 * 	protoc-gen-tsjson v0.5.0
 * 	protoc            v3.10.1
 * source: user.proto
 */

import * as tsjson from "@llkennedy/protoc-gen-tsjson";

/** A message */
export class UserID extends Object implements tsjson.ProtoJSONCompatible {
	/** A field */
	public uuid?: string;
	public ToProtoJSON(): Object {
		return {
			uuid: tsjson.ToProtoJSON.String(this.uuid),
		};
	}
	public static async Parse(data: any): Promise<UserID> {
		let objData: Object = tsjson.AnyToObject(data);
		let res = new UserID();
		res.uuid = await tsjson.Parse.String(objData, "uuid", "uuid");
		return res;
	}
}

